# src/models/cost_model.py
# calculates financial metrics (see line 375).

from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class CostInput:
    """
    Input assumptions for project cost and financial evaluation.

    Version 1 assumptions:
    - PV generation used onsite reduces grid electricity purchase.
    - Renewable electricity purchase adds a premium cost.
    - Renewable purchase does not reduce the normal electricity tariff.
    - PV CAPEX occurs in year 0.
    - PV OPEX occurs annually.
    - Cash flows are evaluated over the project lifetime.
    """

    annual_electricity_demand_kwh: float
    electricity_price_sgd_per_kwh: float

    project_lifetime_years: int
    discount_rate: float

    # Optional escalation assumptions
    electricity_price_escalation_rate_per_year: float = 0.0
    pv_opex_escalation_rate_per_year: float = 0.0
    renewable_premium_escalation_rate_per_year: float = 0.0

    # PV system
    pv_capacity_kwp: float = 0.0
    pv_capex_sgd_per_kwp: float = 0.0
    pv_opex_fraction_of_capex_per_year: float = 0.0
    pv_generation_used_onsite_year1_kwh: float = 0.0
    pv_degradation_rate_per_year: float = 0.0

    # Renewable electricity purchase
    renewable_purchase_kwh_per_year: float = 0.0
    renewable_premium_sgd_per_kwh: float = 0.0


@dataclass(frozen=True)
class AnnualCashFlow:
    year: int
    pv_generation_used_onsite_kwh: float
    renewable_purchase_kwh: float
    electricity_price_sgd_per_kwh: float
    baseline_grid_cost_sgd: float
    project_grid_cost_sgd: float
    electricity_savings_sgd: float
    pv_opex_sgd: float
    renewable_purchase_premium_sgd: float
    net_savings_sgd: float
    discounted_net_savings_sgd: float


@dataclass(frozen=True)
class CostResult:
    baseline_annual_grid_cost_year1_sgd: float
    project_annual_grid_cost_year1_sgd: float

    pv_capex_sgd: float
    annual_pv_opex_year1_sgd: float
    annual_renewable_purchase_premium_year1_sgd: float

    annual_electricity_savings_year1_sgd: float
    annual_net_savings_year1_sgd: float

    present_value_of_net_savings_sgd: float # current worth of a future sum of money
    npv_sgd: float # net present value (NPV) is the total PV of all expected future cash inflows minus the PV of cash outflows
    simple_payback_years: Optional[float]
    discounted_payback_years: Optional[float] # discounted payback period is the time it takes for the sum of the discounted cash flows to equal the initial investment

    pv_lcoe_sgd_per_kwh: Optional[float] # levelized cost of electricity (LCOE) represents the average net present value of the unit-cost of electricity generated by a power plant over its entire operational lifetime. 
    lifetime_baseline_grid_cost_sgd: float
    lifetime_project_grid_cost_sgd: float
    lifetime_electricity_savings_sgd: float
    lifetime_pv_opex_sgd: float
    lifetime_renewable_purchase_premium_sgd: float
    lifetime_net_savings_sgd: float

    annual_cashflows: list[AnnualCashFlow]


def _validate_cost_input(cost_input: CostInput) -> None: # helper function
    if cost_input.annual_electricity_demand_kwh < 0:
        raise ValueError("annual_electricity_demand_kwh cannot be negative.")

    if cost_input.electricity_price_sgd_per_kwh < 0:
        raise ValueError("electricity_price_sgd_per_kwh cannot be negative.")

    if cost_input.project_lifetime_years <= 0:
        raise ValueError("project_lifetime_years must be positive.")

    if cost_input.discount_rate <= -1:
        raise ValueError("discount_rate must be greater than -1.")

    if cost_input.pv_capacity_kwp < 0:
        raise ValueError("pv_capacity_kwp cannot be negative.")

    if cost_input.pv_capex_sgd_per_kwp < 0:
        raise ValueError("pv_capex_sgd_per_kwp cannot be negative.")

    if cost_input.pv_opex_fraction_of_capex_per_year < 0:
        raise ValueError("pv_opex_fraction_of_capex_per_year cannot be negative.")

    if cost_input.pv_generation_used_onsite_year1_kwh < 0:
        raise ValueError("pv_generation_used_onsite_year1_kwh cannot be negative.")

    if not 0 <= cost_input.pv_degradation_rate_per_year < 1:
        raise ValueError("pv_degradation_rate_per_year must be between 0 and 1.")

    if cost_input.renewable_purchase_kwh_per_year < 0:
        raise ValueError("renewable_purchase_kwh_per_year cannot be negative.")

    if cost_input.renewable_premium_sgd_per_kwh < 0:
        raise ValueError("renewable_premium_sgd_per_kwh cannot be negative.")


def calculate_discount_factor(year: int, discount_rate: float) -> float: # helper function
    """
    Calculate discount factor for a given year.

    Year 0 has discount factor 1.
    Year 1 has discount factor 1 / (1 + r).
    """
    if year < 0:
        raise ValueError("year cannot be negative.")

    if discount_rate <= -1:
        raise ValueError("discount_rate must be greater than -1.")

    return 1 / ((1 + discount_rate) ** year)


def calculate_present_value_of_annual_amount(
    annual_amount_sgd: float,
    discount_rate: float,
    project_lifetime_years: int,
) -> float:
    """
    Present value of a constant annual amount from year 1 to project lifetime.
    Useful for quick tests and simple benchmark checks.
    """
    if project_lifetime_years <= 0:
        raise ValueError("project_lifetime_years must be positive.")

    present_value = 0.0

    for year in range(1, project_lifetime_years + 1):
        present_value += annual_amount_sgd * calculate_discount_factor(
            year=year,
            discount_rate=discount_rate,
        )

    return present_value # return total present value of all annual payments from year 1 (not year 0) to end of project lifetime.


def calculate_pv_capex( # helper function
    pv_capacity_kwp: float,
    pv_capex_sgd_per_kwp: float,
) -> float:
    if pv_capacity_kwp < 0:
        raise ValueError("pv_capacity_kwp cannot be negative.")

    if pv_capex_sgd_per_kwp < 0:
        raise ValueError("pv_capex_sgd_per_kwp cannot be negative.")

    return pv_capacity_kwp * pv_capex_sgd_per_kwp


def calculate_discounted_payback_year( # helper function
    pv_capex_sgd: float,
    annual_cashflows: list[AnnualCashFlow], # AnnualCashFlow is a dataclass defined above. 
) -> Optional[float]:
    """
    Calculate the first year when cumulative discounted savings recover CAPEX.

    Returns None if payback is not reached.
    """
    if pv_capex_sgd <= 0:
        return None

    cumulative_discounted_savings = 0.0

    for cashflow in annual_cashflows:
        cumulative_discounted_savings += cashflow.discounted_net_savings_sgd

        if cumulative_discounted_savings >= pv_capex_sgd:
            return float(cashflow.year)

    return None


def calculate_pv_lcoe( # the average net cost of generating one unit of electricity (e.g., 1 kWh) over the system's entire operational lifetime
    pv_capex_sgd: float,
    annual_cashflows: list[AnnualCashFlow],
    discount_rate: float,
) -> Optional[float]:
    """
    Calculate simplified PV LCOE.

    LCOE = discounted PV cost / discounted PV generation used onsite

    In Version 1, this is based on PV generation used onsite, not exported PV. 
    Only PV electricity that is actually used by the building is counted. If excess PV is exported to the grid, it is ignored.
    """
    if pv_capex_sgd <= 0:
        return None

    discounted_pv_opex = 0.0
    discounted_generation = 0.0 # starting value is zero, will accumulate over the years 

    for cashflow in annual_cashflows:
        discount_factor = calculate_discount_factor(
            year=cashflow.year,
            discount_rate=discount_rate,
        )

        discounted_pv_opex += cashflow.pv_opex_sgd * discount_factor
        discounted_generation += (
            cashflow.pv_generation_used_onsite_kwh * discount_factor
        ) # electricity generation is discounted as well. 

    if discounted_generation <= 0:
        return None

    return (pv_capex_sgd + discounted_pv_opex) / discounted_generation


def calculate_costs(cost_input: CostInput) -> CostResult:
    """
    Calculate cost and financial metrics for Version 1.

    Key accounting logic:
    - Baseline grid cost = full demand × electricity price.
    - Project grid cost = remaining grid demand after onsite PV × electricity price.
    - Renewable purchase adds a premium cost.
    - Renewable purchase is used for emissions accounting, not grid bill reduction.
    """
    _validate_cost_input(cost_input)

    pv_capex = calculate_pv_capex(
        pv_capacity_kwp=cost_input.pv_capacity_kwp,
        pv_capex_sgd_per_kwp=cost_input.pv_capex_sgd_per_kwp,
    )

    annual_pv_opex_year1 = (
        pv_capex * cost_input.pv_opex_fraction_of_capex_per_year
    )

    annual_cashflows: list[AnnualCashFlow] = [] # will be used to store one AnnualCashFlow object for every year

    for year in range(1, cost_input.project_lifetime_years + 1): # annual calculation loop 
        electricity_price = cost_input.electricity_price_sgd_per_kwh * (
            (1 + cost_input.electricity_price_escalation_rate_per_year)
            ** (year - 1)
        ) 

        pv_generation_used_onsite = (
            cost_input.pv_generation_used_onsite_year1_kwh
            * ((1 - cost_input.pv_degradation_rate_per_year) ** (year - 1))
        )

        pv_generation_used_onsite = min(
            pv_generation_used_onsite,
            cost_input.annual_electricity_demand_kwh,
        ) # prevent pv use from exceeding electricity demand. 

        renewable_premium = cost_input.renewable_premium_sgd_per_kwh * (
            (1 + cost_input.renewable_premium_escalation_rate_per_year)
            ** (year - 1)
        )

        renewable_purchase_kwh = min(
            cost_input.renewable_purchase_kwh_per_year,
            cost_input.annual_electricity_demand_kwh,
        )

        baseline_grid_cost = (
            cost_input.annual_electricity_demand_kwh * electricity_price
        )

        remaining_grid_consumption = max(
            cost_input.annual_electricity_demand_kwh - pv_generation_used_onsite,
            0,
        )

        project_grid_cost = remaining_grid_consumption * electricity_price

        electricity_savings = baseline_grid_cost - project_grid_cost

        pv_opex = annual_pv_opex_year1 * (
            (1 + cost_input.pv_opex_escalation_rate_per_year) ** (year - 1)
        )

        renewable_purchase_premium = renewable_purchase_kwh * renewable_premium

        net_savings = (
            electricity_savings
            - pv_opex
            - renewable_purchase_premium
        )

        discounted_net_savings = net_savings * calculate_discount_factor(
            year=year,
            discount_rate=cost_input.discount_rate,
        )

        annual_cashflows.append(
            AnnualCashFlow(
                year=year,
                pv_generation_used_onsite_kwh=pv_generation_used_onsite,
                renewable_purchase_kwh=renewable_purchase_kwh,
                electricity_price_sgd_per_kwh=electricity_price,
                baseline_grid_cost_sgd=baseline_grid_cost,
                project_grid_cost_sgd=project_grid_cost,
                electricity_savings_sgd=electricity_savings,
                pv_opex_sgd=pv_opex,
                renewable_purchase_premium_sgd=renewable_purchase_premium,
                net_savings_sgd=net_savings,
                discounted_net_savings_sgd=discounted_net_savings,
            )
        )

    first_year = annual_cashflows[0]

    present_value_of_net_savings = sum(
        cashflow.discounted_net_savings_sgd for cashflow in annual_cashflows
    )

    npv = -pv_capex + present_value_of_net_savings

    if pv_capex > 0 and first_year.net_savings_sgd > 0:
        simple_payback = pv_capex / first_year.net_savings_sgd # simplified estimate because it assumes the first-year savings continue unchanged.
    else:
        simple_payback = None

    discounted_payback = calculate_discounted_payback_year(
        pv_capex_sgd=pv_capex,
        annual_cashflows=annual_cashflows,
    )

    pv_lcoe = calculate_pv_lcoe(
        pv_capex_sgd=pv_capex,
        annual_cashflows=annual_cashflows,
        discount_rate=cost_input.discount_rate,
    )

    lifetime_baseline_grid_cost = sum(
        cashflow.baseline_grid_cost_sgd for cashflow in annual_cashflows
    )

    lifetime_project_grid_cost = sum(
        cashflow.project_grid_cost_sgd for cashflow in annual_cashflows
    )

    lifetime_electricity_savings = sum(
        cashflow.electricity_savings_sgd for cashflow in annual_cashflows
    )

    lifetime_pv_opex = sum(
        cashflow.pv_opex_sgd for cashflow in annual_cashflows
    )

    lifetime_renewable_purchase_premium = sum(
        cashflow.renewable_purchase_premium_sgd for cashflow in annual_cashflows
    )

    lifetime_net_savings = sum(
        cashflow.net_savings_sgd for cashflow in annual_cashflows
    )

    return CostResult( # output data for 4 main groups - year 1 values, investment metrics, lifetime totals, detailed yearly data. 
        baseline_annual_grid_cost_year1_sgd=first_year.baseline_grid_cost_sgd,
        project_annual_grid_cost_year1_sgd=first_year.project_grid_cost_sgd,
        pv_capex_sgd=pv_capex,
        annual_pv_opex_year1_sgd=first_year.pv_opex_sgd,
        annual_renewable_purchase_premium_year1_sgd=(
            first_year.renewable_purchase_premium_sgd
        ),
        annual_electricity_savings_year1_sgd=first_year.electricity_savings_sgd,
        annual_net_savings_year1_sgd=first_year.net_savings_sgd,
        present_value_of_net_savings_sgd=present_value_of_net_savings,
        npv_sgd=npv,
        simple_payback_years=simple_payback,
        discounted_payback_years=discounted_payback,
        pv_lcoe_sgd_per_kwh=pv_lcoe,
        lifetime_baseline_grid_cost_sgd=lifetime_baseline_grid_cost,
        lifetime_project_grid_cost_sgd=lifetime_project_grid_cost,
        lifetime_electricity_savings_sgd=lifetime_electricity_savings,
        lifetime_pv_opex_sgd=lifetime_pv_opex,
        lifetime_renewable_purchase_premium_sgd=lifetime_renewable_purchase_premium,
        lifetime_net_savings_sgd=lifetime_net_savings,
        annual_cashflows=annual_cashflows,
    )
